name: Publish NPM Package

on:
  release:
    types: [created]

jobs:
  call-build-and-test:
    uses: singintime/batch-task/.github/workflows/build-and-test.yml@main

  publish-npm:
    needs: call-build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
